### ISSUE TITLE
식당 상세 조회 기능 개발

### ISSUE THREAD

**Issue by syoh98** [f-lab-edu/go-table#13]
<img src="https://github.com/f-lab-edu/go-table/assets/76934280/628b1ea4-97d1-40e4-b851-bcfeda8b2820" width="800"/>

## 📝 플로우차트
![image](https://github.com/f-lab-edu/go-table/assets/76934280/9848c535-042a-40ec-85b8-68e3eb013f78)

## 📝 TODO
* 식당 상세 조회 API 정의
  |기능|HTTP 메서드|API Path|Request|Response|
  |---|---|---|---|---|
  |식당 상세 조회|GET|` /stores/{id}`|-|-|
  * Reponse
    * Response Elements
      |필드|타입|필수여부|설명|
      |---|---|---|---|
      |status|String|필수|상태코드|
      |data|T|필수|데이터|
      |message|String|필수|메세지|
    * Body
       * 식당 상세 조회 성공 **(200 OK)**
       ```json
       {
         "status": "success",
         "data": {
           "store": {
             "id": 1037,
             "name": "차알 엘지아트센터 서울점",
             "address": "서울 강서구 마곡중앙로 136 지하1층",
             "openSchedule": "매일 오전 11:00 ~ 12:00"
             "maxMemberCount": 8,
             "maxAvailableDay": 7,
             "availableDays": {
               "2024-07-02": {
                 "workSchedule": {
                   "open": "07:00",
                   "close": "10:00"
                 },
                 "selectableTimes": ["07:00", "08:00", "09:00"]
               },
               "2024-07-03": {
                 "workSchedule": {
                   "open": "07:00",
                   "close": "20:00"
                 },
                 "selectableTimes": ["19:00"]
               }
             }
           },
           "message": "식당 상세 조회 성공"
        }
        ```       
       * 식당 상세 조회 실패 - 존재하지 않는 식당 id **(404 Not Found)**
       ```json
        {
          "status": "fail",
          "data": null,
          "message": "존재하지 않는 식당 id입니다."
        }
        ```

**Comment by f-lab-maverick** [comment]
1, 위 그림의 Flow 변경이 필요합니다.
Lock을 획득한 이후 예약이 가능한지 여부를 확인해야 합니다. 락은 실제로 예약하기 버튼을 누른 후 진행됩니다. 그 때 실제로 해당 예약내역에 대해 예약을 할 수 있는지/없는지에 대한 정보를 획득하는 것은 임계영역 내부에서 이루어저야 하기 떄문이에요.
락 없이 예약 가능/불가능 여부를 확인한 후
예약을 한다면
해당 '예약시간'이라는 공유자원에 대해 두가지 액션이 락 없이 수행됩니다. 즉 예약이 가능한지/불가능한지를 판단하는 로직은 락 획득 이후 진행되어야 해요.

![image](https://github.com/f-lab-edu/go-table/assets/131429812/39201770-2ff5-4385-91d8-4e25ac79fa3f)

**Comment by f-lab-maverick** [comment]
2. 데이터 Response의 변경을 해보시겠어요?
현재 식당 상세조회의 구조는 "모든 날짜의 예약 시작/종료 시간이 동일한" 구조입니다. ERD상에는 특수영업 스케줄 등이 있기 떄문에 예약 시작/종료시간이 날짜별로 달라질 수 있을텐데 현재 Response 구조에서는 그런 데이터를 보여줄 수 없습니다.
아래와 같이 날짜와 시간을 계층구조로 만든다면 좀 더 유연한 데이터를 만들 수 있지 않을까요?
```
"data": {
  "store": {
    "availableDays": [
      "2024-07-02": {
        "workSchedule": {
          "open": "07:00",
          "close": "10:00"
        },
        "selectableTimes": ["07:00", "08:00", "09:00"]
      },
      "2024-07-03": {
        "workSchedule": {
          "open": "07:00",
          "close": "20:00"
        },
        "selectableTimes": ["19:00"]
       }
    ]
  }
}
```
